# Generated by Django 4.1.6 on 2023-02-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='fridge_refer',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
