# Generated by Django 4.1.6 on 2023-02-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_list',
            new_name='list_id',
        ),
    ]
