# Generated by Django 4.1.6 on 2023-02-20 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='names',
        ),
    ]
