# Generated by Django 4.1.6 on 2023-02-24 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_rename_product_list_product_list_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='FridgeProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='listaccess',
            name='user',
        ),
        migrations.AddField(
            model_name='listaccess',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
