# Generated by Django 4.1.6 on 2023-02-20 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_list', '0002_rename_name_product_names'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='names',
            new_name='name',
        ),
    ]
